apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demo-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: my-secret
        image: ghcr.io/prathyushasai/demo-app:fa0fd508eb4c2c86ef3253e63613174f7d2fde00
        name: demo-app
        ports:
        - containerPort: 8080
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret
spec:
  data:
  - remoteRef:
      key: /value3
      version: v1
    secretKey: secret-key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: my-secret
